### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by awesomekid1021** [victorquanlam/cryptopunk-nft-generator#2]
Now I'm a little new to this but the code works really well, it's just that when I try to add my own pictures it doesn't generate any copies with them, how do I fix this?

**Comment by victorquanlam** [comment]
Where do you add your pictures? Did you notice the total outputs increase? Unless you limit the outputs number it should generate all the copies. It would be great if you can folk the code and add the pictures so I can have a thorough look. Thanks
